# Prepared data exploration

In [9]:
import numpy as np
import h5py 

In [21]:
a1cr1_data = np.load("data/s3dis/pointcnn/Area_1/copyRoom_1/xyzrgb.npy")
a1cr1_label = np.load("data/s3dis/pointcnn/Area_1/conferenceRoom_1/label.npy")

filename = "data/s3dis/pointcnn/Area_1/conferenceRoom_1/half_0.h5"

with h5py.File(filename, 'r') as f:
    # List all groups
    print("Keys: %s" % f.keys())
    a_group_key = list(f.keys())[0]

    # Get the data
    a1cr1_half = list(f[a_group_key])


Keys: <KeysViewHDF5 ['data', 'data_num', 'indices_split_to_full', 'label', 'label_seg']>


In [22]:
np.average(a1cr1_data, axis=0)

array([-11.53756722,  10.68209421,   1.38419927, 142.41922579,
       140.42352564, 127.03838544])

In [7]:
a1cr1_label[9877:10000,]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [31]:
np.average(a1cr1_half[0], axis=0)

array([-0.49983923, -0.48528674,  1.69690503,  0.53280867,  0.52728295,
        0.47551461,  0.04828692,  0.05919446,  0.532613  ])

In [26]:
a1r1_data = np.load("data/s3dis/pointcnn/Area_1/copyRoom_1/xyzrgb.npy")
a1r2_data = np.load("data/s3dis/pointcnn/Area_1/conferenceRoom_1/xyzrgb.npy")
a1r3_data = np.load("data/s3dis/pointcnn/Area_1/conferenceRoom_2/xyzrgb.npy")

a1 = np.zeros((1,6))
a1 = np.vstack((a1, a1r1_data))
a1 = np.vstack((a1, a1r2_data))
a1 = np.vstack((a1, a1r3_data))

np.average(a1, axis=0)



array([ -8.70937007,  25.98776789,   1.51410476, 133.18344395,
       129.96089212, 119.9002142 ])

In [29]:
a1r3_data


array([[  0.329,  21.489,   0.659,  30.   ,  30.   ,  28.   ],
       [  0.346,  21.513,   0.787,  78.   ,  77.   ,  72.   ],
       [  0.383,  21.495,   0.808,  26.   ,  26.   ,  26.   ],
       ...,
       [ -1.875,  23.533,   0.809,  93.   , 122.   , 180.   ],
       [ -1.884,  23.531,   0.811,  86.   , 103.   , 147.   ],
       [ -1.885,  23.534,   0.814,  78.   ,  89.   , 119.   ]])

In [35]:
seg_data =np.load("/home/guslun/master_thesis_code/dataprep/kvarn_liten/segment_3/xyzrgb.npy")
seg_label =np.load("/home/guslun/master_thesis_code/dataprep/kvarn_liten/segment_3/labels.npy")
seg_label[0:10]

array([[3.],
       [1.],
       [3.],
       [1.],
       [1.],
       [3.],
       [3.],
       [1.],
       [1.],
       [3.]])